apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
    runPolicy: "Serial"
    triggers:
    - type: "GitHub"
      github:
        secret: rahasia
    - type: "Generic"
      generic:
        secret: rahasia
    - type: "ConfigChange"
    - imageChangeParams:
        automatic: true
    source:
      git:
        uri: https://github.com/vohanks354/django-helloword.git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    output:
      pullSecret:
        - name: credquay
      to:
        kind: "ImageStreamTag"
        name: "hello-world:latest"
