apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
spec:
  # hostname: foo.apps.CLUSTER.ccs.ornl.gov
  port:
    targetPort: tcp-80
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nginx-lb
    weight: 100
  wildcardPolicy: None
